### ISSUE TITLE
Statistics for private repo contribution 

### ISSUE THREAD

**Issue by MadhabaPatra** [remotion-dev/github-unwrapped-2022#10]
Have an option to create the unwrapped video for private repo contribution. Using secret keys or user login.

**Comment by levex** [comment]
This would great! Hopefully it happens. :-)

**Comment by JonnyBurger** [comment]
Great idea!

For this year I need to spend my time maintaining the current operation and making sure nothing breaks, but I will seriously consider this for next year. I understand the majority of users do commits in closed-source so this would be a nice optimization.
