### ISSUE TITLE
Most productive day not showing

### ISSUE THREAD

**Issue by MattIPv4** [remotion-dev/github-unwrapped-2022#12]
When viewing the most productive day stat, the bar for the most productive day (Sunday for me) did not render. Interestingly this rendering issue only happens in the browser -- the video download shows the bar on Sunday as expected.

Browser is Firefox Developer Edition 109.0b2 (64-bit), on macOS 12.6.

| Browser | Video |
|-|-|
| ![image](https://user-images.githubusercontent.com/12371363/208572886-9c646136-9335-4447-ac14-ef12319c4097.png) | ![image](https://user-images.githubusercontent.com/12371363/208572946-0ab0e535-ddb0-4489-ad3e-b391c9d82553.png) |

**Comment by liamengland1** [comment]
Yep, same on my end in Firefox release. Eventually it shows up if you pause and unpause a few times, or try to inspect the bar in devtools, which makes it hard to debug. This happens going all the way back to January 2021 builds of Firefox (tested with mozregression), so not a recent issue...

**Comment by JonnyBurger** [comment]
Thanks for reporting! Deploying a fix now!
Need to test more with Firefox in the future...
