### ISSUE TITLE
Language check up

### ISSUE THREAD

**Issue by ELIJAHKUNGU** [remotion-dev/github-unwrapped-2022#14]
Hello I think there is a problem in identifying the languages 
It cannot  identify the frameworks like React, Next js  it is classifying everything as js 
I would recommend the use of a file extension to identify the language

**Comment by JonnyBurger** [comment]
TypeScript, JavaScript etc. are languages, React, Next.js are frameworks.
Therefore I think it is labeled correctly!

Also, this is the classification that GitHub uses for repositories, so we cannot influence it.
