### ISSUE TITLE
Are issues = pullrequests?

### ISSUE THREAD

**Issue by JoshuaBehrens** [remotion-dev/github-unwrapped-2022#16]
I am mostly solving issues directly as pull requests. I know that issues and pull requests are sometimes handled equally. Is this the same statistic or is it just a new value one could add to the video?

**Comment by JonnyBurger** [comment]
No, issues are just issues and pull requests don't count.
I'll consider adding pull requests next year for those users who have more interesting pull request statistics next year!

**Comment by JoshuaBehrens** [comment]
Would you accept pull requests, that include that feature for this year?

**Comment by JonnyBurger** [comment]
@JoshuaBehrens Yes! Two requirements, it needs to be a good experience for all users (fallback if you have no data) and have the same level of rendering performance as the existing scenes. Would be very cool!

**Comment by JoshuaBehrens** [comment]
<img width="580" alt="image" src="https://user-images.githubusercontent.com/1133593/209261290-944315f6-e725-4bd0-9888-e57c2b079595.png">

@JonnyBurger what do you think?
