### ISSUE TITLE
Can we have gitlab-unwrapped feature also?

### ISSUE THREAD

**Issue by GOTAM672** [remotion-dev/github-unwrapped-2022#17]
Many users have there open-source contribution and repository on GitLab. If same feature is also available for GitLab then it would be great.

**Comment by JonnyBurger** [comment]
We will not do this because we have collaborated with GitHub this year.
Feel free to fork and adapt it for your needs though!

**Comment by GOTAM672** [comment]
Thnaks.

**Comment by GOTAM672** [comment]
If supposed i have to change the code for gitlab , then which files i have to do changes.  Can you give some hints or guide me.
