### ISSUE TITLE
Most used languages error

### ISSUE THREAD

**Issue by sayamalvi** [remotion-dev/github-unwrapped-2022#18]
I have never used Jupyter but it's being displayed in top 3 languages. 
![Screenshot_20221221-161958__01](https://user-images.githubusercontent.com/52599441/208888022-7a733ff8-7516-4ee1-9fdf-e31e857fd558.jpg)
![Screenshot_20221221-161914__01](https://user-images.githubusercontent.com/52599441/208888035-d0e70909-bcd8-4319-813a-7916496a6741.jpg)

**Comment by JonnyBurger** [comment]
Thanks! Fixed and reset the video for you.
