### ISSUE TITLE
The number of commits doesn't reflect the actual number of commits I have. 

### ISSUE THREAD

**Issue by Blessing988** [remotion-dev/github-unwrapped-2022#24]
I tried watching my video and realised I have 158 commits instead of 200+ commits. 

Is the number of commits fixed to a specific date or timeline within the month.

This is my [MyGitHubUnwrapped ](https://www.githubunwrapped.com/Blessing988)

**Comment by pernydev** [comment]
Private repos don't count.

**Comment by Blessing988** [comment]
> 

Oh okay thanks.
