### ISSUE TITLE
It does not updates the number of issues opened. I recently resolved it but it still shows the same.

### ISSUE THREAD

**Issue by shatanshu3006** [remotion-dev/github-unwrapped-2022#25]
Same goes for the number of commits.

**Comment by JonnyBurger** [comment]
Hi @shatanshu3006, indeed the number of commits is cached. I have reset the statistics for you now!

**Comment by shatanshu3006** [comment]
> Hi @shatanshu3006, indeed the number of commits is cached. I have reset the statistics for you now!

Great!!
