### ISSUE TITLE
What is the refresh frequency?

### ISSUE THREAD

**Issue by varunkumar** [remotion-dev/github-unwrapped-2022#26]
How often does GitHub refresh the stats? The tool still shows the same stats as the first day I tried it, and it doesn't include contributions made in the last couple of days.

**Comment by igorskyflyer** [comment]
Same here, I guess it fetches it once and then caches it, it hasn't updated since I first tried it. 🙁

**Comment by JonnyBurger** [comment]
Indeed, we cache everything indefinitely. Next year we'll try to include a reset button!

For now, I have reset your statistics manually, so you can now retry!
