### ISSUE TITLE
how does one plan for creating unwrapped for private Github Enterprise Server

### ISSUE THREAD

**Issue by goverdhan07** [remotion-dev/github-unwrapped-2022#27]
I was just curious, If I want to create unwrapped for private Github Enterprise Server how does one proceed? 🤔

**Comment by JonnyBurger** [comment]
I never worked with Enterprise server, but the one change you would have to make is to call a different endpoint. Right now we call the public API in `remotion/github-api.ts` and maybe you could change that to use your Enterprise Server!

Note that if you use Remotion in a company you will also need a company license: https://companies.remotion.dev
