### ISSUE TITLE
Error 404 Page not found.

### ISSUE THREAD

**Issue by allansifuna** [remotion-dev/github-unwrapped-2022#28]
I got an error 404 whilst trying to generate my unwrapped video.

**Comment by amalpotra** [comment]
Hey @allansifuna, its working fine for me. Maybe you can try checking with some other issue at you end.
https://www.githubunwrapped.com/allansifuna

**Comment by allansifuna** [comment]
I think the issue has to do with the Opera browser, since i can access the page using firefox and curl but i get an error 404 when i try with opera browser.
