### ISSUE TITLE
Stats update refresh rate & Bug

### ISSUE THREAD

**Issue by IndigoWizard** [remotion-dev/github-unwrapped-2022#29]
Is it possible to refresh the scrapped stats or does the app retrieve stats only first time it's used?
Also a weird thing; I updated my profile picture after I tried the app, it does show on the video on the website but when I download the video and play it it still show the old profile picture (github default).
___
#### How to reproduce the bug(? /if it is one/ )
- Use the app + download video
- Change profile picture + make new commits /PRs merge... etc
- Re-use the app after change: shows updated profile picture as expected + does not show updated stats
- Download new video
- **Result:** still shows old profile picture on the downloaded video + same old stats

#### Expected behavior
- Show new stats when reusing the app after new commits/PRs merged 
- Show updated profile picture on downloaded video like it shows on the website video

**Comment by JonnyBurger** [comment]
Indeed the statistics are cached indefinitely, this is to keep costs down and allow you to come back after you've generated your video. We will implement a reset button for next year, for now I've reset your page so you can get a new video :)
