### ISSUE TITLE
Video includes information after 2022

### ISSUE THREAD

**Issue by TSRBerry** [remotion-dev/github-unwrapped-2022#31]
Hello!

While I was trying this out I noticed that the example pull request shown in the video were all from 2023 instead of 2022 like I expected.
Is this expected behavior or should it not include any PRs/issues created after 2022?

**Comment by russellbanks** [comment]
From [githubunwrapped.com/about](https://www.githubunwrapped.com/about):

> The data cutoff is approximately 24 hours before you generated the video.

**Comment by JonnyBurger** [comment]
Thanks! I partially solved this problem in https://github.com/remotion-dev/github-unwrapped-2022/pull/32.

The contributions can be filtered to only include the 2022 data, but issues and pull requests cannot. I'll raise this with GitHub  for next year!
