### ISSUE TITLE
Stuck at "wrapping" page

### ISSUE THREAD

**Issue by edmer664** [remotion-dev/github-unwrapped-2022#33]
![image](https://user-images.githubusercontent.com/64422131/211718706-af455fd3-19f7-4483-820c-42da3842633a.png)

![image](https://user-images.githubusercontent.com/64422131/211718769-dcb0e6c1-05a0-49b3-8452-9d59dabdacaa.png)
![image](https://user-images.githubusercontent.com/64422131/211718789-0fd045d1-b120-4e2a-8ebd-c587dbadbcb0.png)

**Comment by E3TU** [comment]
Same problem

**Comment by JonnyBurger** [comment]
Fixed in 72c9c4d5496f752d3a7b52972671ad18b4b1f2ae, sorry about this 🙏 thanks for reporting!
