### ISSUE TITLE
Questions specific to Algorithm & stats

### ISSUE THREAD

**Issue by Anmol-Baranwal** [remotion-dev/github-unwrapped-2022#36]
> Please add a label `question` to this issue.

- When will this be shifted from `2022` to `2023`?
- Can we ignore any language shown in the stats `top languages`?
- How does it prioritize the sweet PR, is it from the stars of the repository or is it just random?

**Comment by JonnyBurger** [comment]
1. 2023 will be a separate repo
2. We'll consider adding some fine-tuning to the 2023 version! This repository is frozen as the campaign has effectively finished
3. It is semi-random, you can see the algorithm in the api folder of this repo.

**Comment by Anmol-Baranwal** [comment]
Thanks for the information.
