### ISSUE TITLE
 issue related to GitHub Unwrapped video

### ISSUE THREAD

**Issue by hashaam-zahid** [remotion-dev/github-unwrapped-2022#41]
I have an issue related to GitHub Unwrapped video. If I enter the username and generate the video, and later my GitHub account gets updated with achievements like merged pull requests, the generated video does not reflect these updates. There should be a functionality to automatically update the video when my GitHub account updates. Additionally, it's crucial that only the user with access to this account can generate the video, preventing others who know the username from creating it.

**Comment by JonnyBurger** [comment]
In the 2023 video, we fixed this and let you reset the video.
For this project however, the cutoff date is December 31st 2022.
