### ISSUE TITLE
Bug spotted while downloading

### ISSUE THREAD

**Issue by Sulagna-Dutta-Roy** [remotion-dev/github-unwrapped-2022#6]
Whenever I tried to download it's failed and showing some bugs in backend. 

Error: 404

![IMG_20221219_224843](https://user-images.githubusercontent.com/72568715/208483794-5fc504b3-aef0-4c38-8aff-654b6237e0d0.jpg)

**Comment by JonnyBurger** [comment]
Sorry your render failed! I just retried it and should be good now! https://www.githubunwrapped.com/Sulagna-Dutta-Roy
Will do a root cause analysis soon.
